// Mocks generated by Mockito 5.3.0 from annotations
// in firmware_updater/test/daemon_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i2;

import 'package:firmware_updater/service.dart' as _i3;
import 'package:fwupd/fwupd.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFile_0 extends _i1.SmartFake implements _i2.File {
  _FakeFile_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [FwupdService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFwupdService extends _i1.Mock implements _i3.FwupdService {
  MockFwupdService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.FwupdStatus get status => (super.noSuchMethod(Invocation.getter(#status),
      returnValue: _i4.FwupdStatus.unknown) as _i4.FwupdStatus);
  @override
  int get percentage =>
      (super.noSuchMethod(Invocation.getter(#percentage), returnValue: 0)
          as int);
  @override
  String get daemonVersion =>
      (super.noSuchMethod(Invocation.getter(#daemonVersion), returnValue: '')
          as String);
  @override
  _i5.Stream<_i4.FwupdDevice> get deviceAdded =>
      (super.noSuchMethod(Invocation.getter(#deviceAdded),
              returnValue: _i5.Stream<_i4.FwupdDevice>.empty())
          as _i5.Stream<_i4.FwupdDevice>);
  @override
  _i5.Stream<_i4.FwupdDevice> get deviceChanged =>
      (super.noSuchMethod(Invocation.getter(#deviceChanged),
              returnValue: _i5.Stream<_i4.FwupdDevice>.empty())
          as _i5.Stream<_i4.FwupdDevice>);
  @override
  _i5.Stream<_i4.FwupdDevice> get deviceRemoved =>
      (super.noSuchMethod(Invocation.getter(#deviceRemoved),
              returnValue: _i5.Stream<_i4.FwupdDevice>.empty())
          as _i5.Stream<_i4.FwupdDevice>);
  @override
  _i5.Stream<List<String>> get propertiesChanged =>
      (super.noSuchMethod(Invocation.getter(#propertiesChanged),
              returnValue: _i5.Stream<List<String>>.empty())
          as _i5.Stream<List<String>>);
  @override
  _i5.Future<void> init() => (super.noSuchMethod(Invocation.method(#init, []),
      returnValue: _i5.Future<void>.value(),
      returnValueForMissingStub: _i5.Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
      Invocation.method(#dispose, []),
      returnValue: _i5.Future<void>.value(),
      returnValueForMissingStub: _i5.Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<_i2.File> download(String? url) =>
      (super.noSuchMethod(Invocation.method(#download, [url]),
              returnValue: _i5.Future<_i2.File>.value(
                  _FakeFile_0(this, Invocation.method(#download, [url]))))
          as _i5.Future<_i2.File>);
  @override
  _i5.Future<void> activate(String? id) => (super.noSuchMethod(
      Invocation.method(#activate, [id]),
      returnValue: _i5.Future<void>.value(),
      returnValueForMissingStub: _i5.Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> clearResults(String? id) => (super.noSuchMethod(
      Invocation.method(#clearResults, [id]),
      returnValue: _i5.Future<void>.value(),
      returnValueForMissingStub: _i5.Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<List<_i4.FwupdDevice>> getDevices() =>
      (super.noSuchMethod(Invocation.method(#getDevices, []),
              returnValue:
                  _i5.Future<List<_i4.FwupdDevice>>.value(<_i4.FwupdDevice>[]))
          as _i5.Future<List<_i4.FwupdDevice>>);
  @override
  _i5.Future<List<_i4.FwupdRelease>> getDowngrades(String? deviceId) =>
      (super.noSuchMethod(Invocation.method(#getDowngrades, [deviceId]),
          returnValue: _i5.Future<List<_i4.FwupdRelease>>.value(
              <_i4.FwupdRelease>[])) as _i5.Future<List<_i4.FwupdRelease>>);
  @override
  _i5.Future<List<_i4.FwupdPlugin>> getPlugins() =>
      (super.noSuchMethod(Invocation.method(#getPlugins, []),
              returnValue:
                  _i5.Future<List<_i4.FwupdPlugin>>.value(<_i4.FwupdPlugin>[]))
          as _i5.Future<List<_i4.FwupdPlugin>>);
  @override
  _i5.Future<List<_i4.FwupdRelease>> getReleases(String? deviceId) =>
      (super.noSuchMethod(Invocation.method(#getReleases, [deviceId]),
          returnValue: _i5.Future<List<_i4.FwupdRelease>>.value(
              <_i4.FwupdRelease>[])) as _i5.Future<List<_i4.FwupdRelease>>);
  @override
  _i5.Future<List<_i4.FwupdRemote>> getRemotes() =>
      (super.noSuchMethod(Invocation.method(#getRemotes, []),
              returnValue:
                  _i5.Future<List<_i4.FwupdRemote>>.value(<_i4.FwupdRemote>[]))
          as _i5.Future<List<_i4.FwupdRemote>>);
  @override
  _i5.Future<List<_i4.FwupdRelease>> getUpgrades(String? deviceId) =>
      (super.noSuchMethod(Invocation.method(#getUpgrades, [deviceId]),
          returnValue: _i5.Future<List<_i4.FwupdRelease>>.value(
              <_i4.FwupdRelease>[])) as _i5.Future<List<_i4.FwupdRelease>>);
  @override
  _i5.Future<void> install(String? id, _i2.ResourceHandle? handle,
          {Set<_i4.FwupdInstallFlag>? flags = const {}}) =>
      (super.noSuchMethod(
              Invocation.method(#install, [id, handle], {#flags: flags}),
              returnValue: _i5.Future<void>.value(),
              returnValueForMissingStub: _i5.Future<void>.value())
          as _i5.Future<void>);
  @override
  _i5.Future<void> unlock(String? id) => (super.noSuchMethod(
      Invocation.method(#unlock, [id]),
      returnValue: _i5.Future<void>.value(),
      returnValueForMissingStub: _i5.Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> verify(String? id) => (super.noSuchMethod(
      Invocation.method(#verify, [id]),
      returnValue: _i5.Future<void>.value(),
      returnValueForMissingStub: _i5.Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> verifyUpdate(String? id) => (super.noSuchMethod(
      Invocation.method(#verifyUpdate, [id]),
      returnValue: _i5.Future<void>.value(),
      returnValueForMissingStub: _i5.Future<void>.value()) as _i5.Future<void>);
}
