// Mocks generated by Mockito 5.3.0 from annotations
// in firmware_updater/test/page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:firmware_updater/daemon.dart' as _i3;
import 'package:firmware_updater/model.dart' as _i7;
import 'package:firmware_updater/state.dart' as _i2;
import 'package:fwupd/fwupd.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFwupdState_0 extends _i1.SmartFake implements _i2.FwupdState {
  _FakeFwupdState_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [FwupdDaemon].
///
/// See the documentation for Mockito's code generation for more information.
class MockFwupdDaemon extends _i1.Mock implements _i3.FwupdDaemon {
  MockFwupdDaemon() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.FwupdStatus get status => (super.noSuchMethod(Invocation.getter(#status),
      returnValue: _i4.FwupdStatus.unknown) as _i4.FwupdStatus);
  @override
  int get percentage =>
      (super.noSuchMethod(Invocation.getter(#percentage), returnValue: 0)
          as int);
  @override
  String get version =>
      (super.noSuchMethod(Invocation.getter(#version), returnValue: '')
          as String);
  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i5.Future<void> init() => (super.noSuchMethod(Invocation.method(#init, []),
      returnValue: _i5.Future<void>.value(),
      returnValueForMissingStub: _i5.Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
      Invocation.method(#dispose, []),
      returnValue: _i5.Future<void>.value(),
      returnValueForMissingStub: _i5.Future<void>.value()) as _i5.Future<void>);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
  @override
  void addListener(_i6.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i6.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
}

/// A class which mocks [FwupdModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockFwupdModel extends _i1.Mock implements _i7.FwupdModel {
  MockFwupdModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FwupdState get state => (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakeFwupdState_0(this, Invocation.getter(#state)))
      as _i2.FwupdState);
  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i5.Future<void> init() => (super.noSuchMethod(Invocation.method(#init, []),
      returnValue: _i5.Future<void>.value(),
      returnValueForMissingStub: _i5.Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> refresh() => (super.noSuchMethod(
      Invocation.method(#refresh, []),
      returnValue: _i5.Future<void>.value(),
      returnValueForMissingStub: _i5.Future<void>.value()) as _i5.Future<void>);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  _i5.Future<void> install(
          _i4.FwupdDevice? device, _i4.FwupdRelease? release) =>
      (super.noSuchMethod(Invocation.method(#install, [device, release]),
              returnValue: _i5.Future<void>.value(),
              returnValueForMissingStub: _i5.Future<void>.value())
          as _i5.Future<void>);
  @override
  _i5.Future<void> verify(_i4.FwupdDevice? device) => (super.noSuchMethod(
      Invocation.method(#verify, [device]),
      returnValue: _i5.Future<void>.value(),
      returnValueForMissingStub: _i5.Future<void>.value()) as _i5.Future<void>);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
  @override
  void addListener(_i6.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i6.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
}
