// Mocks generated by Mockito 5.3.0 from annotations
// in firmware_updater/test/service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:firmware_updater/service.dart' as _i2;
import 'package:fwupd/fwupd.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FwupdService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFwupdService extends _i1.Mock implements _i2.FwupdService {
  MockFwupdService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FwupdStatus get status => (super.noSuchMethod(Invocation.getter(#status),
      returnValue: _i3.FwupdStatus.unknown) as _i3.FwupdStatus);
  @override
  int get percentage =>
      (super.noSuchMethod(Invocation.getter(#percentage), returnValue: 0)
          as int);
  @override
  String get daemonVersion =>
      (super.noSuchMethod(Invocation.getter(#daemonVersion), returnValue: '')
          as String);
  @override
  _i4.Stream<_i3.FwupdDevice> get deviceAdded =>
      (super.noSuchMethod(Invocation.getter(#deviceAdded),
              returnValue: _i4.Stream<_i3.FwupdDevice>.empty())
          as _i4.Stream<_i3.FwupdDevice>);
  @override
  _i4.Stream<_i3.FwupdDevice> get deviceChanged =>
      (super.noSuchMethod(Invocation.getter(#deviceChanged),
              returnValue: _i4.Stream<_i3.FwupdDevice>.empty())
          as _i4.Stream<_i3.FwupdDevice>);
  @override
  _i4.Stream<_i3.FwupdDevice> get deviceRemoved =>
      (super.noSuchMethod(Invocation.getter(#deviceRemoved),
              returnValue: _i4.Stream<_i3.FwupdDevice>.empty())
          as _i4.Stream<_i3.FwupdDevice>);
  @override
  _i4.Stream<List<String>> get propertiesChanged =>
      (super.noSuchMethod(Invocation.getter(#propertiesChanged),
              returnValue: _i4.Stream<List<String>>.empty())
          as _i4.Stream<List<String>>);
  @override
  _i4.Future<void> init() => (super.noSuchMethod(Invocation.method(#init, []),
      returnValue: _i4.Future<void>.value(),
      returnValueForMissingStub: _i4.Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
      Invocation.method(#dispose, []),
      returnValue: _i4.Future<void>.value(),
      returnValueForMissingStub: _i4.Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> activate(_i3.FwupdDevice? device) => (super.noSuchMethod(
      Invocation.method(#activate, [device]),
      returnValue: _i4.Future<void>.value(),
      returnValueForMissingStub: _i4.Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> clearResults(_i3.FwupdDevice? device) => (super.noSuchMethod(
      Invocation.method(#clearResults, [device]),
      returnValue: _i4.Future<void>.value(),
      returnValueForMissingStub: _i4.Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<List<_i3.FwupdDevice>> getDevices() =>
      (super.noSuchMethod(Invocation.method(#getDevices, []),
              returnValue:
                  _i4.Future<List<_i3.FwupdDevice>>.value(<_i3.FwupdDevice>[]))
          as _i4.Future<List<_i3.FwupdDevice>>);
  @override
  _i4.Future<List<_i3.FwupdRelease>> getDowngrades(String? deviceId) =>
      (super.noSuchMethod(Invocation.method(#getDowngrades, [deviceId]),
          returnValue: _i4.Future<List<_i3.FwupdRelease>>.value(
              <_i3.FwupdRelease>[])) as _i4.Future<List<_i3.FwupdRelease>>);
  @override
  _i4.Future<List<_i3.FwupdPlugin>> getPlugins() =>
      (super.noSuchMethod(Invocation.method(#getPlugins, []),
              returnValue:
                  _i4.Future<List<_i3.FwupdPlugin>>.value(<_i3.FwupdPlugin>[]))
          as _i4.Future<List<_i3.FwupdPlugin>>);
  @override
  _i4.Future<List<_i3.FwupdRelease>> getReleases(String? deviceId) =>
      (super.noSuchMethod(Invocation.method(#getReleases, [deviceId]),
          returnValue: _i4.Future<List<_i3.FwupdRelease>>.value(
              <_i3.FwupdRelease>[])) as _i4.Future<List<_i3.FwupdRelease>>);
  @override
  _i4.Future<List<_i3.FwupdRemote>> getRemotes() =>
      (super.noSuchMethod(Invocation.method(#getRemotes, []),
              returnValue:
                  _i4.Future<List<_i3.FwupdRemote>>.value(<_i3.FwupdRemote>[]))
          as _i4.Future<List<_i3.FwupdRemote>>);
  @override
  _i4.Future<List<_i3.FwupdRelease>> getUpgrades(String? deviceId) =>
      (super.noSuchMethod(Invocation.method(#getUpgrades, [deviceId]),
          returnValue: _i4.Future<List<_i3.FwupdRelease>>.value(
              <_i3.FwupdRelease>[])) as _i4.Future<List<_i3.FwupdRelease>>);
  @override
  _i4.Future<void> install(
          _i3.FwupdDevice? device, _i3.FwupdRelease? release) =>
      (super.noSuchMethod(Invocation.method(#install, [device, release]),
              returnValue: _i4.Future<void>.value(),
              returnValueForMissingStub: _i4.Future<void>.value())
          as _i4.Future<void>);
  @override
  _i4.Future<void> unlock(_i3.FwupdDevice? device) => (super.noSuchMethod(
      Invocation.method(#unlock, [device]),
      returnValue: _i4.Future<void>.value(),
      returnValueForMissingStub: _i4.Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> verify(_i3.FwupdDevice? device) => (super.noSuchMethod(
      Invocation.method(#verify, [device]),
      returnValue: _i4.Future<void>.value(),
      returnValueForMissingStub: _i4.Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> verifyUpdate(_i3.FwupdDevice? device) => (super.noSuchMethod(
      Invocation.method(#verifyUpdate, [device]),
      returnValue: _i4.Future<void>.value(),
      returnValueForMissingStub: _i4.Future<void>.value()) as _i4.Future<void>);
}
