include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.mocks.dart"
    - "**/*_localizations*.dart"

linter:
  rules:
    avoid_classes_with_only_static_members: false
    avoid_redundant_argument_values: true
    directives_ordering: true
    prefer_relative_imports: true
    sort_pub_dependencies: true
