name: firmware_updater
description: Firmware Updater
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  collection: ^1.17.2
  dbus: ^0.7.8
  dio: ^5.3.3
  file: ^7.0.0
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  fwupd:
    git:
      url: https://github.com/d-loose/fwupd.dart
      ref: refresh-property-cache
  gtk: ^2.1.0
  handy_window: ^0.4.0
  meta: ^1.9.1
  path: ^1.8.3
  provider: ^6.0.5
  safe_change_notifier: ^0.4.0
  ubuntu_logger: ^0.2.0
  ubuntu_service: ^0.4.0
  ubuntu_test: ^0.2.0
  upower: ^0.7.0
  xdg_directories: ^1.0.4
  yaml: ^3.1.2
  yaru: ^5.0.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  integration_test:
    sdk: flutter
  mockito: ^5.4.2
  ubuntu_lints: ^0.4.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
