name: firmware-updater
version: git
summary: Firmware Updater
description: Update Firmware
confinement: strict
base: core22
grade: stable
license: GPL-3.0+
icon: snap/local/firmware-updater.png
architectures:
  - build-on: amd64

slots:
  dbus-slot:
    interface: dbus
    name: com.canonical.firmware_updater
    bus: session

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-tag: 3.10.6
    source-depth: 1
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/dart $CRAFT_PART_INSTALL/usr/bin/dart
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime: ''

  firmware-updater-app:
    after: [ flutter-git ]
    plugin: nil
    source: .
    override-build: |
      # when building locally artifacts can pollute the container and cause builds to fail
      # this helps increase reliability for local builds
      flutter clean
      flutter pub get
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/

  firmware-notifier:
    after: [ flutter-git, firmware-updater ]
    plugin: nil
    source: ./packages/firmware_notifier/
    override-build: |
      set -eux
      dart pub get
      mkdir -p $CRAFT_PART_INSTALL/bin/
      dart compile exe bin/firmware_notifier.dart -o $CRAFT_PART_INSTALL/bin/firmware-notifier

  firmware-updater:
    plugin: dump
    source: ./launcher-script/

apps:
  firmware-updater:
    command: bin/launch-firmware-updater.sh
    desktop: bin/data/flutter_assets/assets/firmware-updater.desktop
    extensions: [gnome]

  firmware-updater-app:
    command: bin/firmware-updater --gapplication-service
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on: [dbus-slot]
    extensions: [gnome]
    plugs:
      - fwupd
      - upower-observe

  firmware-notifier:
    command: bin/firmware-notifier
    daemon: simple
    passthrough:
      daemon-scope: user
    timer: '00:00-24:00/8'
    extensions: [gnome]
    plugs:
      - desktop
      - fwupd
      - upower-observe
