name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.10.x'

jobs:
  analyze:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: flutter pub global activate melos
      - run: melos pub get
      - run: melos analyze

  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: flutter pub global activate melos
      - run: melos pub get
      - run: melos format

  mocks:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: flutter pub global activate melos
      - run: melos pub get
      - run: melos generate
      - name: Check for outdated mocks
        if: github.event_name != 'push'
        run: ./.github/scripts/check-outdated-files.sh
      - name: Create PR
        if: github.event_name == 'push'
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: '**/*.mocks.dart'
          title: 'chore: regenerate mocks'
          commit-message: 'chore: regenerate mocks'
          branch: create-pull-request/mocks
          delete-branch: true

  l10n:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: flutter pub global activate melos
      - run: melos pub get
      - run: melos gen-l10n
      - name: Check for outdated l10n
        if: github.event_name == 'pull_request'
        run: ./.github/scripts/check-outdated-files.sh
      - name: Create PR
        if: github.event_name == 'push'
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: '**/l10n/*.dart'
          title: 'chore: regenerate l10n'
          commit-message: 'chore: regenerate l10n'
          branch: create-pull-request/l10n
          delete-branch: true

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: sudo apt update && sudo apt install -y lcov
      - run: flutter pub global activate melos
      - run: melos pub get
      - run: melos coverage
      - uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}

  integration:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: ${{env.FLUTTER_VERSION}}
    - run: sudo apt update
    - run: sudo apt install -y clang cmake curl dbus dbus-x11 fwupd fwupd-tests gsettings-desktop-schemas libgtk-3-dev ninja-build pkg-config unzip upower xvfb
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: Prepare environment
      run: |
        sudo sed -i 's/DisabledPlugins=.*/DisabledPlugins=invalid;bios/g' /etc/fwupd/daemon.conf
        echo "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$UID/bus" >> $GITHUB_ENV
        echo "XDG_RUNTIME_DIR=/run/user/$UID" >> $GITHUB_ENV
        gsettings set org.gnome.desktop.interface gtk-theme 'Yaru'
    - run: sudo fwupdmgr enable-remote fwupd-tests
    - run: sudo fwupdmgr get-devices
    - run: sudo -E xvfb-run -a -s '-screen 0 1024x768x24 +extension GLX' $FLUTTER_ROOT/bin/flutter test integration_test
