name: OSV-Scanner

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  scan-push:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@764c91816374ff2d8fc2095dab36eecd42d61638" # v1.9.2
    with:
      scan-args: |-
        -r
        ./

  scan-pr:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@764c91816374ff2d8fc2095dab36eecd42d61638" # v1.9.2
    with:
      scan-args: |-
        -r
        ./
