name: OSV-Scanner

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  scan-push:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@9bb69575e74019c2ad085a1860787043adf47ccb" # v2.2.4
    with:
      scan-args: |-
        -r
        ./

  scan-pr:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@9bb69575e74019c2ad085a1860787043adf47ccb" # v2.2.4
    with:
      scan-args: |-
        -r
        ./
