name: Snap

on:
  schedule:
  - cron:  '45 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: snapcore/action-build@v1
      id: snapcraft
    - uses: actions/upload-artifact@v4
      if: github.event_name == 'workflow_dispatch'
      with:
        name: 'snap'
        path: ${{steps.snapcraft.outputs.snap}}
